import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import { FaLinkedin, FaInstagram, FaGithub } from "react-icons/fa";
import Link from "components/link";

const SCHeader = styled.header`
  margin-top: 2.5em;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  h1 {
    margin: 1em 0;
  }

  .image {
    border-radius: 50%;
  }
`;

const SCLinksButtonSection = styled.section`
  margin: 1em auto;
`;

const SCFooter = styled.footer`
  display: flex;
  flex: 1;
  padding: 2rem 0;
  justify-content: center;
  align-items: center;
  position: fixed;
  bottom: 0;
  width: 100vw;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <SCHeader>
        <Image
          src="/avatar.png"
          alt="Vercel Logo"
          width={150}
          height={150}
          className="image"
          style={{ background: "transparent" }}
        />
        <h1>Rafał Apriasz</h1>
        <p>Software Engineer speciliazed in frontend technologies</p>
      </SCHeader>
      <SCLinksButtonSection>
        <Link icon={<FaGithub />} to="www.google.pl" title="Github" />
        <Link icon={<FaInstagram />} to="www.google.pl" title="Instagram" />
        <Link icon={<FaLinkedin />} to="www.google.pl" title="Linkedin" />
        <Link to="to:mailto@gmail.com" title="Contact me" />
      </SCLinksButtonSection>
      <SCFooter>
        <p>© Copyright 2022</p>
      </SCFooter>
    </>
  );
};

export default Home;
