import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.image} />
        <h1 className={styles.title}>Rafał Apriasz</h1>
        <div className={styles.links}>
          <a className={styles.link}>My Website 1</a>
          <a className={styles.link}>My Blog</a>
          <a className={styles.link}>My Website 2</a>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>© Copyright 2022</p>
      </footer>
    </div>
  );
};

export default Home;
